name: Docs

on:
  push:
    branches:
      - master
  pull_request:

env:
  IsPR: "no"

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

  languagetool:
    name: LanguageTool Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: reviewdog/action-languagetool@v1.9.0
        with:
          github_token: ${{ secrets.github_token }}
          language: en-CA
          level: warning

  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if PR
        if: github.event_name == 'pull_request'
        run: |
          echo "IsPR='yes'" >> "$GITHUB_ENV"
      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          config-file: ".github/mlc_config.json"
          check-modified-files-only: "${{ env.IsPR }}"
